### ISSUE TITLE
Data object in documentation is wrong 

### ISSUE THREAD

**Issue by mjrode** [raphi/jwplayer-api-client#1]
There is an error in your documentation 

`data = {
  author:        'Raphaël',
  date:          Date.new(2002,03,04).to_time.to_i,
  description:   'Yet Another Keynote',
  title:         'Apple Keynote',
  source_format: :m3u8,
  source_type:   :url,
  source_url:    'http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8'
}
`

When you make the request with the data object written like this you get a ':ok' response but the video does not actually get added to JWplayer. 

After reading through the documentation I found what the error is.[https://developer.jwplayer.com/jw-platform/reference/v1/methods/videos/create.html](Docs.)

You need to remove the underscores so the data object looks like this. 

`data = {
  author:        'Raphaël',
  date:          Date.new(2002,03,04).to_time.to_i,
  description:   'Yet Another Keynote',
  title:         'Apple Keynote',
  sourceformat: :m3u8,
  sourcetype:   :url,
  sourceurl:    'http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8'
}
`

**Comment by raphi** [comment]
Hi @mjrode ,

thanks for reporting this and sorry for the inconvenience! I just fixed the documentation.
FYI I never saw this bug because I was just retrieving the `media id`.

Thanks!

**Comment by mjrode** [comment]
Thanks for the gem it is going to save me a ton of time. I am glad I could
help.
