### ISSUE TITLE
How to extract PlayerID?

### ISSUE THREAD

**Issue by BallerChan** [raphi/jwplayer-api-client#2]
The mediaID is returned via the response in the documentation but I am not sure how to get the playerID? I need both to generate a custom embed link.

**Comment by raphi** [comment]
Hi @BallerChan 

I'm not sure what's your need but let's start with the following example:

I found an API call to get all players here: 
https://developer.jwplayer.com/jw-platform/reference/v1/methods/players/list.html

So using this gem, you would do something like this:

```ruby
require 'typhoeus'

jw_client  = JWPlayer::API::Client.new
signed_url = jw_client.signed_url('players/list')
response   = Typhoeus.post(signed_url)
json       = JSON.parse(response.body)
```

The returned data looks like this:

```ruby
irb(main):155:0> pp json
{"status"=>"ok",
 "rate_limit"=>{"reset"=>1488877080, "limit"=>60, "remaining"=>59},
 "players"=>
  [{"views"=>42,
    "key"=>"MzKlIya7",
    "skin"=>{"type"=>"built-in", "name"=>"Default", "key"=>"N13KUxt9"},
    "responsive"=>true,
    "aspectratio"=>"16:9",
    "playlist"=>"none",
    "release_channel"=>"production",
    "name"=>"16:9 example player",
    "custom"=>{"hlshtml"=>"true"},
    "version"=>"7",
    "ltas_channel"=>nil},
   {"views"=>0,
    "height"=>270,
    "key"=>"phbBhk8V",
    "skin"=>{"type"=>"built-in", "name"=>"Default", "key"=>"N03KUxu9"},
    "responsive"=>false,
    "playlist"=>"none",
    "release_channel"=>"production",
    "name"=>"480x270 example player",
    "custom"=>{},
    "width"=>480,
    "version"=>"7",
    "ltas_channel"=>nil}],
 "limit"=>50,
 "offset"=>0,
 "total"=>2}
```

From there you can fetch your players ids.

Does that answer your question? If not, please provide more information & documentation about what you are trying to achieve.

**Comment by BallerChan** [comment]
Thanks for the information @raphi! I was messing around with the commands and I ended up doing something like jw_client.signed_url('/players/create') and that provided me with the playerID. This method you provided actually answers a couple other issues I ran into so thank you!

Best,
Chan
